language: scala
scala:
  - 2.12.4
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - github@quadstingray.com
jdk:
  - oraclejdk8
  - openjdk8
script:
  - sbt ^test
addons:
  apt:
    packages:
    - oracle-java8-installer
deploy:
  provider: script
  script: '[ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] &&
    /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && /bin/bash "$TRAVIS_BUILD_DIR/.travis.build.sh"'