language: scala
scala:
  - 2.12.4
branches:
  only:
  - master
before_install:
  - git config --global user.name "$USER"
  - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
  - openssl aes-256-cbc -K $encrypted_4308745bc0f5_key -iv $encrypted_4308745bc0f5_iv -in project/travis-deploy-key.enc -out project/travis-deploy-key -d
  - chmod 600 project/travis-deploy-key
  - eval "$(ssh-agent -s)"
  - ssh-add project/travis-deploy-key
notifications:
  email:
    recipients:
    - github@quadstingray.com
os: linux
jdk:
  - oraclejdk8
  - openjdk8
script:
  - sbt ^test
addons:
  apt:
    packages:
    - oracle-java8-installer
jobs:
  include:
    - stage: Test
      scala: 2.12.4
      script: sbt ^test
      jdk: oraclejdk8
      os: linux
    - scala: 2.12.4
      script: sbt ^test
      jdk: openjdk8
      os: linux
    - stage: SBT Plugin Tests
      scala: 2.12.4
      os: osx
      osx_image: xcode8
      script: - sbt scripted
    - stage: SBT Publish
      scala: 2.12.4
      script: '/bin/bash "$TRAVIS_BUILD_DIR/.travis.publish.sh"'
    - stage: Release and Build Docu
      scala: 2.12.4
      jdk: oraclejdk8
      script: '/bin/bash "$TRAVIS_BUILD_DIR/.travis.release.sh"'