language: scala
scala:
  - 2.12.4
branches:
  only:
  - master
before_deploy:
  - git config --global user.name "$USER"
  - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
  # Decrypt the secret deploy key using instructions from `travis encrypt-file`
  - openssl aes-256-cbc -K $encrypted_4308745bc0f5_key -iv $encrypted_4308745bc0f5_iv -in project/travis-deploy-key.enc -out project/travis-deploy-key -d
  - chmod 600 project/travis-deploy-key
  # Start ssh-agent in the background and load the deploy key
  - eval "$(ssh-agent -s)"
  - ssh-add project/travis-deploy-key


notifications:
  email:
    recipients:
    - github@quadstingray.com
jdk:
  - oraclejdk8
  - openjdk8
script:
  - sbt ^test
addons:
  apt:
    packages:
    - oracle-java8-installer
deploy:
  provider: script
  script: '[ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] &&
    /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && /bin/bash "$TRAVIS_BUILD_DIR/.travis.build.sh"'
  on:
     branch: master
     condition: $TRAVIS_PULL_REQUEST = false