branches:
  only:
  - master
before_install:
- git config --global user.name "$USER"
- git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
# Decrypt the secret deploy key using instructions from `travis encrypt-file`
- openssl aes-256-cbc -K $encrypted_4308745bc0f5_key -iv $encrypted_4308745bc0f5_iv -in project/travis-deploy-key.enc -out project/travis-deploy-key -d
- chmod 600 project/travis-deploy-key
# Start ssh-agent in the background and load the deploy key
- eval "$(ssh-agent -s)"
- ssh-add project/travis-deploy-key
notifications:
  email:
    recipients:
    - github@quadstingray.com
script:
- echo ''
os: linux
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
jobs:
  include:
  - stage: Tests
    name: "Test on Mac with Java 8"
    before_install:
    - brew update
    - brew outdated caskroom/cask/brew-cask || brew upgrade caskroom/cask/brew-cask
    - brew install sbt
    - sudo rm -rf /Library/Java/JavaVirtualMachines
    - brew tap AdoptOpenJDK/openjdk
    - brew install adoptopenjdk-openjdk8
    os: osx
    osx_image: xcode10
    script: sbt ^publishLocal ^scripted
  - stage: Tests
    name: "Test on Mac with Java 9"
    before_install:
    - brew update
    - brew outdated caskroom/cask/brew-cask || brew upgrade caskroom/cask/brew-cask
    - brew install sbt
    - sudo rm -rf /Library/Java/JavaVirtualMachines
    - brew tap AdoptOpenJDK/openjdk
    - brew install adoptopenjdk-openjdk9
    os: osx
    osx_image: xcode10
    script: sbt ^publishLocal ^scripted
  - stage: Tests
    name: "Test on Mac with Java 10"
    before_install:
    - brew update
    - brew outdated caskroom/cask/brew-cask || brew upgrade caskroom/cask/brew-cask
    - brew install sbt
    - sudo rm -rf /Library/Java/JavaVirtualMachines
    - brew tap AdoptOpenJDK/openjdk
    - brew install adoptopenjdk-openjdk10
    os: osx
    osx_image: xcode10
    script: sbt ^publishLocal ^scripted
  - stage: Tests
    name: "Test on Mac with Java 11"
    before_install:
    - brew update
    - brew outdated caskroom/cask/brew-cask || brew upgrade caskroom/cask/brew-cask
    - brew install sbt
    - sudo rm -rf /Library/Java/JavaVirtualMachines
    - sudo mkdir /Library/Java/JavaVirtualMachines
    - cd /Library/Java/JavaVirtualMachines
    - sudo curl https://download.java.net/java/ga/jdk11/openjdk-11_osx-x64_bin.tar.gz -O
    - sudo tar xvf openjdk-11*_bin.tar.gz
    - echo "export JAVA_HOME=/Library/Java/JavaVirtalMachines/jdk-11.jdk/Contents/Home" >> ~/.bash_profile
    - source ~/.bash_profile
    - cd $TRAVIS_BUILD_DIR
    os: osx
    osx_image: xcode10
    script: sbt clean ^publishLocal '^scripted sbt-javafx/antjar-change'
  - stage: Publish
    language: scala
    scala: 2.12.7
    os: linux
    jdk: openjdk11
    script: '/bin/bash "$TRAVIS_BUILD_DIR/.travis.publish.sh"'
  - stage: Release and Build Docu
    language: scala
    scala: 2.12.7
    os: linux
    jdk: openjdk11
    script: '/bin/bash "$TRAVIS_BUILD_DIR/.travis.release.sh"'