branches:
  only:
  - master
before_install:
  - git config --global user.name "$USER"
  - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
  # Decrypt the secret deploy key using instructions from `travis encrypt-file`
  - openssl aes-256-cbc -K $encrypted_4308745bc0f5_key -iv $encrypted_4308745bc0f5_iv -in project/travis-deploy-key.enc -out project/travis-deploy-key -d
  - chmod 600 project/travis-deploy-key
  # Start ssh-agent in the background and load the deploy key
  - eval "$(ssh-agent -s)"
  - ssh-add project/travis-deploy-key
notifications:
  email:
    recipients:
    - github@quadstingray.com
script:
  - echo ''
os: linux
addons:
  apt:
    packages:
    - oracle-java8-installer
jobs:
  include:
    - stage: SBT Test
      language: scala
      scala: 2.12.5
      os: linux
      jdk: oraclejdk8
      script: 'sbt ^test'
    - scala: 2.12.5
      language: scala
      os: linux
      jdk: openjdk8
      script: 'sbt ^test'
    - before_install:
        - brew update
        - brew outdated caskroom/cask/brew-cask || brew upgrade caskroom/cask/brew-cask
        - sudo rm -rf /Library/Java/JavaVirtualMachines
        - brew cask install caskroom/versions/java8
        - brew install sbt
      os: osx
      osx_image: xcode8
      script: sbt ^publishLocal ^scripted
    - stage: SBT Publish
      language: scala
      scala: 2.12.5
      os: linux
      jdk: oraclejdk8
      script: '/bin/bash "$TRAVIS_BUILD_DIR/.travis.publish.sh"'
    - stage: Release and Build Docu
      language: scala
      scala: 2.12.5
      os: linux
      jdk: oraclejdk8
      script: '/bin/bash "$TRAVIS_BUILD_DIR/.travis.release.sh"'