language: scala
scala:
  - 2.12.4
branches:
  only:
  - master
before_install:
  - git config --global user.name "$USER"
  - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
  - openssl aes-256-cbc -K $encrypted_4308745bc0f5_key -iv $encrypted_4308745bc0f5_iv -in project/travis-deploy-key.enc -out project/travis-deploy-key -d
  - chmod 600 project/travis-deploy-key
  - eval "$(ssh-agent -s)"
  - ssh-add project/travis-deploy-key
notifications:
  email:
    recipients:
    - github@quadstingray.com
jdk:
  - openjdk8
script:
  - sbt ^test
jobs:
  include:
    - stage: SBT Tests
      scala: 2.12.4
      os: osx
      script: sbt ^test
    - stage: SBT publish
      scala: 2.12.4
      script: '/bin/bash "$TRAVIS_BUILD_DIR/.travis.publish.sh"'
    - stage: Release and Build Docu
      scala: 2.12.4
      jdk: oraclejdk8
      script: '/bin/bash "$TRAVIS_BUILD_DIR/.travis.release.sh"'